import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-loading-skeleton/dist/skeleton.css'
import SessionLayout from "../layout/SessionLayout";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionLayout>
      <html lang="en">
        <body >
          <Header />
          {children}
          <Footer/>
        </body>
      </html>
    </SessionLayout>
  );
}
